spring:
  main:
    banner-mode: "off"
  application:
    name: ${APP_NAME:gabelstrapler-observability-app}

use-cases:
  endpoint-one: ${USE_CASES_ENDPOINT_1:}
  endpoint-two: ${USE_CASES_ENDPOINT_2:}
  scheduler-endpoint: ${USE_CASES_SCHEDULER_ENDPOINT:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name:}
  otlp:
    tracing:
      endpoint: ${TRACING_URL:http://localhost:4317}
    metrics:
      export:
        enabled: false

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
