spring:
  application:
    name: gabelstrapler-observability-app-1

use-cases:
  endpoint-one: http://localhost:8081
  endpoint-two: ${USE_CASES_ENDPOINT_2:}
  scheduler-endpoint: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACING_URL:http://localhost:4317}
    metrics:
      export:
        enabled: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
