spring:
  application:
    name: gabelstrapler-observability-app-2

server:
  port: 8081

use-cases:
  endpoint-one: ${USE_CASES_ENDPOINT_1:}
  endpoint-two: ${USE_CASES_ENDPOINT_2:}
  scheduler-endpoint: ${USE_CASES_SCHEDULER_ENDPOINT:}
