spring:
  application:
    name: gabelstrapler-observability-app-1

use-cases:
  endpoint-one: http://localhost:8081
  endpoint-two: ${USE_CASES_ENDPOINT_2:}
  scheduler-endpoint: http://localhost:8080