spring:
  application:
    name: gabelstrapler-observability-app-2

server:
  port: 8081

use-cases:
  endpoint-one: ${USE_CASES_ENDPOINT_1:}
  endpoint-two: ${USE_CASES_ENDPOINT_2:}
  scheduler-endpoint: ${USE_CASES_SCHEDULER_ENDPOINT:}

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACING_URL:http://localhost:4317}
    metrics:
      export:
        enabled: false

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
